betagouv/mrs

.circleci/deploy.sh
Dockerfile
src/mrs/settings.py
tox.ini

- smtp configuration,
- db configuration,
- security configuration,

Dynamic settings for production deployment

---

src/mrs/templates/base.html

* Ajout des **majuscules** à MRS 👍 🍺 
* Il manquait un point à la phrase d'accroche

Modifications de texte

---

Dockerfile

https://github.com/unbit/uwsgi/issues/1126

Fugbix file server

---

src/mrs/templates/base.html

Ajout de la dernière Question/Réponse sur la conservation des justificatifs

Add new Q/A

---

src/mrs/static/js/mrsattachment.js
src/mrs/static/sass/upload.sass

fix for single and multiple uploads.
todos:
- tests for mrsattachment.js (some of them can be obtained from upload.test.js)
+ move to webpack pipeline
+ test with jest
+ migrate code to es6
- replace 'effacer' with cross svg img.

manual frontend validation added for mime/type and file size.

---

Dockerfile

https://stackoverflow.com/questions/36156887/uwsgi-raises-oserror-write-error-during-large-request

Fix #143: ignore write errors

---

package.json
src/mrs/settings.py
src/mrs/static/js/statistics.js
src/mrs/static/sass/statistics.sass
src/mrs/urls.py
src/mrspage/templates/mrspage/statistics.html
src/mrspage/urls.py
src/mrspage/views.py
webpack.config.js

Pret a deployer quand vous voulez ;)

Fix #147: add /stats/

---

src/contact/templates/contact/form.html
src/mrs/static/js/base.js
src/mrs/static/js/contact.js
src/mrs/templates/index.html

@fjg @notmoebius vous voyez cette PR ?
Il faudra qu'elle pas et que **rien n'ait changé, tout marche toujours en staging**

Template / JS refactor for multipage development

---

.circleci/config.yml
package.json
src/contact/templates/contact/_form.html
src/mrs/static/js/smoke.test.js
yarn.lock

Just make sure that we don't make a blunt mistake when refactoring
bundles and templates

Smoke tests

---

src/mrs/static/js/base.js
src/mrs/static/js/index.js
src/mrs/templates/index.html

Deleted code is debugged code.

Fix #254: JS Error from Sentry

---

src/institution/urls.py
src/institution/views.py
src/mrs/static/manifest.json
src/mrs/urls.py
src/mrs/views.py

@tbinetruy Il manque les icones du launcher, peux-tu les pousser dans cette branche stp ?

Manifest.json

---

src/mrs/static/sass/index.sass

Vertical alignment issue on mobile, page "legal"

---

src/mrs/jinja2/crudlfap/home.html
src/mrs/static/js/crudlfap.js

- fix element.prototype.closest and element.prototype.matches not supported by IE
- fix mismatched h4 tag

fix prototype is supported by IE

---

src/mrs/static/sass/form.sass
src/mrs/static/sass/index.sass

Fix issue #308
https://github.com/betagouv/mrs/issues/308

Ie display bug

---

src/mrs/templates/legal.html
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/mentions-legales.content

maj mentions legales (dpo, conventions...)

---

LICENSE

create licence AGPLv3

---

requirements.txt
src/mrsrequest/crudlfap.py

Fix export

---

src/mrsuser/crudlfap.py

Back port of awesome hotfix already in production :joy:

Bugfix user create

---

src/mrs/templates/index.html
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/content

Bravo @fb86 d'avoir trouvé le bug !!

Fix #509 again: correct paste of blablablabla

---

requirements.txt
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/content
src/mrs/tests/response_fixtures/StatCrawlTest.test_crawl/admin/content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/content

Normalement fixerait le bug rencontre par un UPN remonte par Jo

Upgrade to CRUDLFA+ 0.4.13

---

src/mrsrequest/templates/mrsrequest/liquidation_validation_mail_body.txt
src/mrsrequest/templates/mrsrequest/liquidation_validation_mail_title.txt

feat(mail): update archive email

---

requirements.txt
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/caisse/create.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/emailtemplate/create.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/institution/create.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/user/create.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/content

upgrade crudlfap with the new translations, update our tests.

update translations (list, create)

---

src/person/management/commands/nir2email.py

from a file of NIRs, print emails.

new script: nir2email

---

src/mrsrequest/tests/test_mrsrequest_admin_progress_reject.json
src/mrsrequest/tests/test_mrsrequest_admin_progress_validate.json
src/mrsrequest/tests/test_mrsrequest_admin_views.py
src/mrsrequest/tests/test_mrsrequest_models.py
src/person/models.py
src/person/tests/test_personmodel.py
tox.ini

Nir 13 model validator

---

src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/13751dc2-18bb-4925-a8b4-84383a042bae.content
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/ad2ac0fd-95e6-4b3f-9a4b-ef581e9e07c2.content
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/c697cf5a-dc4d-434d-89bc-1f606d05d39d.content
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/f5ac697c-d4cd-34d4-89bc-39d1f606dd05.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/13751dc2-18bb-4925-a8b4-84383a042bae.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/770efeec-34a8-49f6-ab04-c6dde9a4a679.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/ad2ac0fd-95e6-4b3f-9a4b-ef581e9e07c2.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/c697cf5a-dc4d-434d-89bc-1f606d05d39d.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/f5ac697c-d4cd-34d4-89bc-39d1f606dd05.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/13751dc2-18bb-4925-a8b4-84383a042bae.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/ad2ac0fd-95e6-4b3f-9a4b-ef581e9e07c2.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/c697cf5a-dc4d-434d-89bc-1f606d05d39d.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/f5ac697c-d4cd-34d4-89bc-39d1f606dd05.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequeststatus=1&sort=creation_datetime.content
src/mrsrequest/crudlfap.py
src/mrsrequest/jinja2/mrsrequest/mrsrequest_detail.html
src/mrsrequest/models.py

Le seul détail qui manque, c'est que le *title* au survol de la souris n'a pas le CSS materialize.
fixes #589

Libelle champs modifies

---

docs/tutorial.rst
src/mrsstat/tests/test_mrsstat.json

bouton loupe: fix other test data (mrsstat.json)

---

src/mrsstat/models.py
src/mrsstat/tests/test_mrsstat.py
src/person/management/commands/update_savings.py

update savings on Person save signal

---

src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/13751dc2-18bb-4925-a8b4-84383a042bae.content
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/ad2ac0fd-95e6-4b3f-9a4b-ef581e9e07c2.content
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/c697cf5a-dc4d-434d-89bc-1f606d05d39d.content
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/f5ac697c-d4cd-34d4-89bc-39d1f606dd05.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/13751dc2-18bb-4925-a8b4-84383a042bae.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/770efeec-34a8-49f6-ab04-c6dde9a4a679.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/ad2ac0fd-95e6-4b3f-9a4b-ef581e9e07c2.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/c697cf5a-dc4d-434d-89bc-1f606d05d39d.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/f5ac697c-d4cd-34d4-89bc-39d1f606dd05.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/13751dc2-18bb-4925-a8b4-84383a042bae.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/ad2ac0fd-95e6-4b3f-9a4b-ef581e9e07c2.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/c697cf5a-dc4d-434d-89bc-1f606d05d39d.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/f5ac697c-d4cd-34d4-89bc-39d1f606dd05.content
src/mrsrequest/crudlfap.py

the date field from the json data, a str, must be parsed to a date.
@jpic  je te laisse 5min pour dicuter du style, du nommage etc ;)

don't always underline birth_date

---

src/mrs/static/js/mrsrequest.js
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/demande.content
src/mrsrequest/forms.py

Les dates sont toutes ensembles grace à ce patch

Regroup date formset

---

src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/ad2ac0fd-95e6-4b3f-9a4b-ef581e9e07c2/validate.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/ad2ac0fd-95e6-4b3f-9a4b-ef581e9e07c2/validate.content
src/mrsrequest/templates/mrsrequest/insured_validation_mail_body.txt

Mail de validation: enlever "simple"

---

src/mrsrequest/crudlfap.py

Champ reply-to manquant sur mail de confirmation de paiement

---

src/contact/templates/contact/form.html
src/mrs/static/sass/form.sass
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/contact.content
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequeststatus=1&sort=creation_datetime.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequeststatus=1&sort=creation_datetime.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequeststatus=1&sort=creation_datetime.content

add contact info (email, tel)

---

src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/demande.content
src/mrsrequest/forms.py

fix form slash typo

---

src/mrsrequest/models.py

if the field changed, take its original value, not the previous
changed one.
for #707

mail archive original nir/birth date: retrieve original value

---

src/mrs/settings.py
src/mrsrequest/models.py

[ci skip]
fixes #658 
@jpic However I don't see sentry config in the loggers (mrs.settings.LOGGING). If not here, how then is Sentry enabled ?

if balance is negative, notify Sentry

---

Dockerfile

This reverts commit a06961b9c6f4bf21c8f18488b6e0f17952a19ff7.

Revert "Cache TTL for static files"

---

docs/tutorial.rst
requirements.txt
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequeststatus=1&sort=creation_datetime.content
src/mrs/tests/response_fixtures/StatCrawlTest.test_crawl/admin/stat/totaldate__gte=01/05/2018&ampdate__lte=31/05/2018.content
src/mrs/tests/response_fixtures/StatCrawlTest.test_crawl/admin/stat/totaldate__gte=01/05/2018&ampdate__lte=31/05/2018.metadata
src/mrs/tests/response_fixtures/StatCrawlTest.test_crawl/admin/statdate__gte=01/05/2018&ampdate__lte=31/05/2018.content
src/mrs/tests/response_fixtures/StatCrawlTest.test_crawl/admin/statdate__gte=01/05/2018&ampdate__lte=31/05/2018.metadata
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequeststatus=1&sort=creation_datetime.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/stat/totaldate__gte=01/05/2018&ampdate__lte=31/05/2018.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/stat/totaldate__gte=01/05/2018&ampdate__lte=31/05/2018.metadata
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/statdate__gte=01/05/2018&ampdate__lte=31/05/2018.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/statdate__gte=01/05/2018&ampdate__lte=31/05/2018.metadata
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequeststatus=1&sort=creation_datetime.content
tox.ini

Includes :
https://github.com/jieter/django-tables2/issues/627

Test tools upgrade

---

src/mrs/static/js/mrsrequest.js
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/demande.content
src/mrsrequest/forms.py
src/mrsrequest/models.py
src/mrsrequest/templates/mrsrequest/_form.html
src/mrsrequest/views.py

Add confirmation page

---

src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/13751dc2-18bb-4925-a8b4-84383a042bae.content
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/767b8123-2134-48cb-8177-0c411309a0b1.content
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/ad2ac0fd-95e6-4b3f-9a4b-ef581e9e07c2.content
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/c697cf5a-dc4d-434d-89bc-1f606d05d39d.content
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/mrsrequest/f5ac697c-d4cd-34d4-89bc-39d1f606dd05.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/13751dc2-18bb-4925-a8b4-84383a042bae.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/35fe2514-b1e7-4f97-955a-f163788afdf3.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/767b8123-2134-48cb-8177-0c411309a0b1.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/770efeec-34a8-49f6-ab04-c6dde9a4a679.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/ad2ac0fd-95e6-4b3f-9a4b-ef581e9e07c2.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/b83cd5c8-ae0a-4efd-b1ba-6e35775f10bb.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/c697cf5a-dc4d-434d-89bc-1f606d05d39d.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/mrsrequest/f5ac697c-d4cd-34d4-89bc-39d1f606dd05.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/13751dc2-18bb-4925-a8b4-84383a042bae.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/767b8123-2134-48cb-8177-0c411309a0b1.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/ad2ac0fd-95e6-4b3f-9a4b-ef581e9e07c2.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/c697cf5a-dc4d-434d-89bc-1f606d05d39d.content
src/mrs/tests/response_fixtures/SupportCrawlTest.test_crawl/admin/mrsrequest/f5ac697c-d4cd-34d4-89bc-39d1f606dd05.content
src/mrsrequest/jinja2/mrsrequest/mrsrequest_detail.html

Detect duplicate dates

---

locale/fr/LC_MESSAGES/django.po
src/contact/forms.py
src/contact/templates/contact/contact_mail_body.txt
src/contact/templates/contact/team_mail_reclamation_mrs.txt
src/contact/templates/contact/team_mail_title.txt
src/contact/tests/test_contactviews.py
src/contact/views.py
src/mrs/static/js/contact.js
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/contact.content
tox.ini

Pour debloquer la MEP de demain car master contient 2 bugfixes critiques.

Formulaire de contact: suite et fin

---

src/mrsrequest/models.py

exclude new requests from duplicates

---

src/mrsrequest/templates/mrsrequest/cancel.html
src/mrsrequest/tests/response_fixtures/cancel_ko_canceled.content
src/mrsrequest/tests/response_fixtures/cancel_ko_inprogress.content
src/mrsrequest/tests/response_fixtures/cancel_ko_rejected.content
src/mrsrequest/tests/response_fixtures/cancel_ko_validated.content
src/mrsrequest/tests/response_fixtures/cancel_ok.content
src/mrsrequest/tests/test_cancel.py
src/mrsrequest/tests/test_mrsrequestcreateview.py

Restent encore une petite series de tests de regressions a ajouter.

Correctifs sur l'annulation

---

src/mrs/templates/legal.html
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/demande.content
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/mentions-legales.content
src/mrsrequest/templates/mrsrequest/_form.html

J'ai mis à jour les fichiers html pour une PR.
Deux fichiers: _form.html et legal.html.
Merci pour la PR et retour.

Legal stuff

---

package.json
requirements.txt
src/contact/crudlfap.py
src/mrs/tests/response_fixtures/LiquidateurCrawlTest.test_crawl/admin/content
src/mrs/tests/response_fixtures/StatCrawlTest.test_crawl/admin/content
src/mrs/tests/response_fixtures/StatCrawlTest.test_crawl/admin/stat/totaldate__gte=01%2F05%2F2018&ampdate__lte=31%2F05%2F2018&ampcaisse=1.content
src/mrs/tests/response_fixtures/StatCrawlTest.test_crawl/admin/stat/totaldate__gte=01%2F05%2F2018&ampdate__lte=31%2F05%2F2018&ampcaisse=1.metadata
src/mrs/tests/response_fixtures/StatCrawlTest.test_crawl/admin/statdate__gte=01%2F05%2F2018&ampdate__lte=31%2F05%2F2018&ampcaisse=1.content
src/mrs/tests/response_fixtures/StatCrawlTest.test_crawl/admin/statdate__gte=01%2F05%2F2018&ampdate__lte=31%2F05%2F2018&ampcaisse=1.metadata
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/contact.content
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/contact.metadata
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/contact/deleteobjects.content
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/contact/deleteobjects.metadata
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/content
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/rating.content
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/rating.metadata
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/stat/totaldate__gte=01%2F05%2F2018&ampdate__lte=31%2F05%2F2018&ampcaisse=1.content
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/stat/totaldate__gte=01%2F05%2F2018&ampdate__lte=31%2F05%2F2018&ampcaisse=1.metadata
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/stat/totaldate__gte=01%2F05%2F2018&ampdate__lte=31%2F05%2F2018.content
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/stat/totaldate__gte=01%2F05%2F2018&ampdate__lte=31%2F05%2F2018.metadata
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/statdate__gte=01%2F05%2F2018&ampdate__lte=31%2F05%2F2018&ampcaisse=1.content
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/statdate__gte=01%2F05%2F2018&ampdate__lte=31%2F05%2F2018&ampcaisse=1.metadata
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/statdate__gte=01%2F05%2F2018&ampdate__lte=31%2F05%2F2018.content
src/mrs/tests/response_fixtures/SuperviseurCrawlTest.test_crawl/admin/statdate__gte=01%2F05%2F2018&ampdate__lte=31%2F05%2F2018.metadata
src/mrsstat/crudlfap.py
src/rating/crudlfap.py
yarn.lock

Architecture immobiliere sur une ligne avec deux colonnes remplies de lignes, plutot que sur une serie de lignes de deux colonnes.
Cela regle le probleme des espaces vides entre les cartes de la page de detail de demande.
A noter que la carte ATP passe au dessus de la carte VP

Remassonnerie page detail de demandes

---

src/mrsrequest/templates/mrsrequest/success_mail_body.txt
src/mrsrequest/tests/test_mrsrequestcreateview.py

Add the total distance in kilometers to the acknowledgment email

---

src/caisse/migrations/0001_squashed_migrations.py
src/institution/migrations/0001_squashed_migrations.py
src/mrsemail/migrations/0001_squashed_migrations.py
src/mrsrequest/migrations/0001_squashed_migrations_step1.py
src/mrsrequest/migrations/0002_squashed_migrations_step2.py
src/mrsstat/migrations/0001_squashed_migrations.py
src/mrsuser/migrations/0001_squashed_migrations.py
src/person/migrations/0002_squashed_migrations.py

Il reste encore pas mal de migrations non squashées pour des apps tierces (djcall, explorer, auth) mais au moins pour les nôtres (mrsrequest notamment) on y voit plus clair !

Squashed migrations

---

.drone.yml
Dockerfile
ansible/requirements.yml
ansible/tasks/backup.yml
ansible/tasks/check.yml
ansible/tasks/docker.yml
ansible/tasks/future.yml
ansible/tasks/logrotate.yml
ansible/tasks/main.yml
ansible/tasks/nginx.yml
ansible/tasks/postgres.yml
ansible/vars/main.yml
do
docker-compose.staging.yml
docker-compose.yml

- Import ansible code into MRS repo (in-progress)
- Deploy with docker-compose, behind traefik, with Drone
- Changed mailcatcher to maildev

Continuous Deployment of staging behind traefik

---

requirements.txt
src/mrs/context_processors.py
src/mrs/jinja2/base.html
src/mrs/settings.py
src/mrs/static/js/crudlfap.js
src/mrs/templates/base.html
src/mrs/urls.py
src/mrs/views.py
webpack.config.js

Migrating to sentry-sdk caused CORS issues & IE11 unsupported javascript functions issues, which impacted mrs-ecole environment. For now we rollback to raven, while investigating on sentrysdk issue-solving.

Back to raven

---

src/contact/tests/test_contactviews.py
src/mrsrequest/models.py
src/mrsrequest/tests/test_mrsrequest_models.py
src/person/tests/test_personform.py

https://sentry.mrs.beta.gouv.fr/sentry/mrs-production/issues/451/?referrer=slack

Fix bug: conflicting display ids, auto-recovery

---

conftest.py
src/caisse/forms.py
src/institution/tests/test_institution_views.py
src/mrs/static/js/mrsrequest.js
src/mrs/static/sass/form.sass
src/mrs/templates/base.html
src/mrs/tests/data.json
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/contact.content
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/content
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/demande.content
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/demande.metadata
src/mrs/tests/response_fixtures/FrontCrawlTest.test_crawl/stats.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/caisse/1.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/caisse/1/update.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/caisse/2.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/caisse/2/update.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/caisse/create.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/caisseactive=2.content
src/mrs/tests/response_fixtures/SuperuserCrawlTest.test_crawl/admin/user.content
src/mrs/tests/test_crawl.py
src/mrsrequest/forms.py
src/mrsrequest/templates/mrsrequest/_form.html
src/mrsrequest/templates/mrsrequest/form.html
src/mrsrequest/tests/test_mrsrequest_form.py
src/mrsrequest/tests/test_mrsrequestcreateview.py
src/mrsrequest/tests/test_mrsrequestcreateview_caisse.json
src/mrsrequest/tests/test_mrsrequestcreateview_caisseemail.json
src/mrsrequest/views.py

Merci à @jpic pour le gros coup de main sur les templates !

Alternative Formulaire régions avec attribut data-region

---

.drone.yml
src/mrs/management/commands/contact_email.py
src/mrs/management/commands/mrsrequest_email.py
src/mrs/settings.py
src/mrsrequest/models.py

Pour renvoyer certains mails quand MailJet a accepté mais n'a pas envoyé pour X raison.

Réponse d'incident mail

---

src/mrsuser/models.py
src/mrsuser/tests/test_mrsuser_models.py

Fixes: conflicts between profiles

Hack user.profile == to support mupltile profiles

---

src/institution/views.py

Fix iframe support with new HTTP security

Switch from deprecated X-Frame-Options to CSP frame-ancestors
